# Generated by Django 5.1.4 on 2025-01-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_category_options_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
